version: "3.7"

services:
  backend:
    build: 
      context: ./
      dockerfile: local.Dockerfile
    container_name: backend
    volumes:
      - ./:/go/src/<project-path>
    ports: 
      - "8083:80"
    depends_on: 
      - "db"
  db:
    image: "postgres:13.1-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: <db-user>
      POSTGRES_PASSWORD: <db-password>
      POSTGRES_DB: <db-name>
